spring.application.name=api
server.port=8080

# Expose the Actuator health endpoint
management.endpoints.web.exposure.include=health

# These are the custom variables we injected into our Repositories using @Value!
# In production, Terraform will overwrite these automatically using environment variables.
app.aws.dynamodb.events-table=sports-tracker-dev-events
app.aws.dynamodb.summaries-table=sports-tracker-dev-summaries

# Turn down noisy AWS SDK logs
logging.level.software.amazon.awssdk=WARN
logging.level.org.springframework.security=WARN
