# Application
spring.application.name=producer

# Actuator — expose the health endpoint for ECS health checks
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Scheduling — how often to poll API-Sports (every 30 seconds)
app.api.sports.poll-interval-ms=30000

# AWS
app.aws.region=us-east-1
app.aws.kinesis.stream-name=sports-tracker-dev-stream
app.aws.secrets.api-sports-key-arn=arn:aws:secretsmanager:us-east-1:412381751532:secret:sports-tracker/dev/api-sports-key-1vbRqS

# API-Sports
app.api.sports.configs.SOCCER.base-url=https://v3.football.api-sports.io
app.api.sports.configs.SOCCER.fixture-id=1128139
app.api.sports.configs.BASKETBALL.base-url=https://v1.basketball.api-sports.io
app.api.sports.configs.BASKETBALL.fixture-id=12345
app.api.sports.configs.FOOTBALL.base-url=https://v1.american-football.api-sports.io
app.api.sports.configs.FOOTBALL.fixture-id=12345
app.api.sports.configs.BASEBALL.base-url=https://v1.baseball.api-sports.io
app.api.sports.configs.BASEBALL.fixture-id=12345
app.api.sports.configs.HOCKEY.base-url=https://v1.hockey.api-sports.io
app.api.sports.configs.HOCKEY.fixture-id=12345
app.api.sports.configs.FORMULA_1.base-url=https://v1.formula-1.api-sports.io
app.api.sports.configs.FORMULA_1.fixture-id=12345
