# Application
spring.application.name=producer

# Actuator — expose the health endpoint for ECS health checks
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Scheduling — how often to poll API-Sports (every 30 seconds)
api.sports.poll-interval-ms=30000

# AWS
aws.region=us-east-1
aws.kinesis.stream-name=sports-tracker-dev-stream
aws.secrets.api-sports-key-arn=arn:aws:secretsmanager:us-east-1:412381751532:secret:sports-tracker/dev/api-sports-key-1vbRqS

# API-Sports
api.sports.base-url=https://v3.football.api-sports.io
api.sports.fixture-id=1128139
